version: 0.2
phases:
  build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID_1}"
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID_2}"
